"""added date joined

Revision ID: 9008a6ad894d
Revises: 7a5a240ffa38
Create Date: 2021-06-21 14:05:37.126608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9008a6ad894d'
down_revision = '7a5a240ffa38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_joined', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_joined')
    # ### end Alembic commands ###
